### ISSUE TITLE
Automate even more the schema generation

### ISSUE THREAD

**Issue by guidomedina** [FasterXML/jackson-dataformat-protobuf#15]
I'm working on a project where I serialize POJO in a binary format to Riak using the Riak Java client which I have modified to accept our own Json mapper, the Riak Java client basically read and writes from/to `byte[]` to POJO using the Json mapper so I'm trying to use the protobuf mapper with Riak but I can't at the moment in its current state.

I'm thinking probably a cache interface that the protobuf mapper is able to use to get the schema for a particular class via `computeIfAbsent` style?, that way the schemas are generated at runtime the first time _-or can be preloaded into the cache passed to the protobuf mapper-_  by the protobuf mapper.

At the moment we are using smile and it works fine, specially because is automatic, I just need to pass our mapper and that's it, so basically I'm trying to drop in protobuf as a replacement.

Do you think is reasonable and possible what I'm asking?

**Comment by guidomedina** [comment]
Edited initial description, it was unclear what I was trying to describe.

**Comment by cowtowncoder** [comment]
Please note that this project has moved to:

https://github.com/FasterXML/jackson-dataformats-binary

But as to issue... not sure I follow: as things are you can create necessary `ProtobufSchema` by one of:

1. Give textual representation to parse: `ProtobufMapper.schemaLoader().load(source)`
2. Generate schema from POJO: `ProtobufMapper.generateSchemaFor(cls)`

which would seem to cover sources I can think of.
Of these, (2) is not necessarily implemented very well yet, and there's certainly work to be done.

But I guess I can see what you are actually asking... that given a type, (2) should be done.
And for that, caching would make sense since generation is relatively expensive operation (plus unnecessary: `Class` implementations can not change during runtime for specific class).

Now... to do that could in theory be done within `ProtobufMapper`, but it would make more sense to allow pluggability via `ObjectMapper` (and `ObjectReader` / `ObjectWriter`) since this could also apply to `Avro` and `CSV` modules which require schemas.

If above is correct, I think you'd actually want to re-file this for `jackson-databind`. Mapper would require some sort of extension point to allow for auto-configuration of schema based on type.
I think this does make sense: and further, it would be possibly to hook up with JAX-RS providers as well.

**Comment by guidomedina** [comment]
Yes, that's exactly what I'm asking, I thought I was on the right project as I know it was moved, somehow I ended up creating in the wrong place, close the issue as I can see you have thought about it even further.

The idea is what you said, to be able to plug that schema generator which for methods like:
- `readValue(byte[] src, Class<T> valueType)` will call the schema generator for `Class<T>`, if using Java 8 it is easy to plug-in a simple cache implementation without any 3rd party.
- `writeValueAsBytes(Object value)` will call the schema generator for `value.getClass()`

You get the idea.

**Comment by cowtowncoder** [comment]
@guidomedina Ah no prob. I went ahead and created:

https://github.com/FasterXML/jackson-databind/issues/1582

which I hope summarizes this fairly. I like the idea, thank you for suggesting it. In fact, I didn't realize this could be a reasonable way to implement JAX-RS providers for Avro/CSV/Properties/Protobuf (although annotation-based approach might work there too).

Jackson 3.x will be able to use Java 8 baseline, fwtw. I don't know if this could be made in time for 2.9 anyway.
