### ISSUE TITLE
Doesn't respect PropertyNamingStrategy

### ISSUE THREAD

**Issue by HiJon89** [FasterXML/jackson-dataformat-protobuf#9]
My protobuf field names are lowercase with underscores as recommended by the [protobuf style guide](https://developers.google.com/protocol-buffers/docs/style) and my POJO field names are camel-case.

It might be worth supporting this by default since I expect it to be the most common configuration (this is what I did for [jackson-datatype-protobuf](https://github.com/HubSpot/jackson-datatype-protobuf)), but I tried to make it work using a `PropertyNamingStrategy` without any luck. I keep getting unrecognized field exceptions (I tried setting the naming strategy on the `ObjectMapper` and on the object via `@JsonNaming`)

**Comment by HiJon89** [comment]
Actually nevermind, it looks like it was due to using a `@JsonCreator` constructor with `@JsonProperty`. The `@JsonProperty` was unaffected by the naming strategy and was also affecting serialization not just deserialization. I had to upgrade Jackson to 2.6.0-rc1 to use this library and it looks like these might just be changes in behavior outside of jackson-dataformat-protobuf

**Comment by cowtowncoder** [comment]
Yes, true, `@JsonProperty` allows specifying explicit external name, regardless of naming strategy.
The problem with `@JsonCreator` is just that Java bytecode does not contain parameter names until Java 8 (or, if using paranamer), so names often need to be added.
But with Java 8, and matching module, you can actually avoid use of `@JsonProperty` as well.

Thank you for checking out this module -- I am very interested in any problems you find.

I also still hope to add two features related to protoc/schema handling, before 2.6.0 finale:

1. Ability to construct protoc schema programmatically (with builder/fluent style, probably)
2. Generation of protoc schema from POJO (class definition), similar to how CSV and Avro modules allow this to be done.

and in both cases should be possible to also write `protoc` serialization (textual definition) out.

One open question is whether object model for protoc should just be one `protoparser` exposes, or a wrapper thereof. I like the idea of reusing something others have done, but doing so may be risky wrt compatibility.

**Comment by jhaber** [comment]
I like the idea of number 1, although I don't think writing .proto files is that much of a burden and it already has a well-defined format (and in our case we already have them written). 

Number 2 kind of scares me, I would be afraid of accidentally changing the serialization/deserialization in a breaking way. Having the .proto is a good sanity check because Jackson can validate that your object matches the desired protobuf definition, but if its introspected it seems easy to accidentally mess up the protobuf format. Also, since field order is significant in protobuf format how would Jackson introspect that? Based on the order in which the fields are defined? Or a field order annotation or something to that effect?

Also, I think defaulting to a `LowerCaseWithUnderscoresStrategy` for this module would be a very convenient behavior since protobuf field names are lowercase with underscores

**Comment by cowtowncoder** [comment]
I think that POJO-generation would probably usually be used to generate schema which is then written out. 

But as to ordering: protobuf does not actually rely on field ordering -- all entries are identified by field id, and order is arbitrary. This allows easy appending of contents, and decoders are required not to count on ordering of fields. This is one of big differences to Avro.

Dataformat modules do not actually have power over naming strategy, so it would be up to user to use an alternative, if they so choose. I assume protobuf allows any naming convention, although I would expect most users to follow one commonly used.
